-------------------------------------------------------------------------------
Test set: se.ecutb.service.PersonDtoConversionServiceTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.054 s <<< FAILURE! - in se.ecutb.service.PersonDtoConversionServiceTest
given_source_convertToPersonDtoWithTodos_return_successfully_and_contains_correct_data  Time elapsed: 0.001 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: not <null>
	at se.ecutb.service.PersonDtoConversionServiceTest.given_source_convertToPersonDtoWithTodos_return_successfully_and_contains_correct_data(PersonDtoConversionServiceTest.java:60)

